ifndef CI
BUILD ?= docker run -it -v $(shell pwd)/lambda/:/code -w /code --entrypoint=npm node:10-alpine update --unsafe-perm=true --allow-root
else
BUILD ?= cd lambda/ && npm update && cd ..
endif

# Ensures that a variable is defined
define assert-set
  @[ -n "$($1)" ] || (echo "$(1) not defined in $(@)"; exit 1)
endef

## Build lambda package
build:
	$(BUILD)
	sudo chmod -R 777 lambda
	mkdir -p artifacts
	cd lambda && zip -r ../artifacts/lambda.zip *

## Verify $EMAIL used as gateway for forwarding
verify-gateway-email:
	$(call assert-set,REGION)
	$(call assert-set,EMAIL)
	aws --region=$(REGION) ses verify-email-identity --email-address $(EMAIL)

